### ISSUE TITLE
tooltips don't move with the page on scroll  when isotip.open is used

### ISSUE THREAD

**Issue by kostisM** [datuhealth/isotip#18]
When i use 
isotip.open( '#trip1', { html: false,   placement: 'top',  content: 'Tooltip content',  title: 'Tooltip title'} ); 
tooltip "stays"  fixed , without changing top or bottom value.

When i use data-attributes everything is ok.

**Comment by mike-engel** [comment]
Thanks for the report @kostisM, I'll try to take a look at this before the weekend.

**Comment by mike-engel** [comment]
Hey @kostisM, this should be fixed in `1.2.5` with commit 2584a8e81a26971a0bf21c7c5ad78127c1aa6a2c. Let me know if you continue having trouble!
